Repository Intel-Edge-AI-SW-Developers-2nd-Team-1/BoardMaestro, pull requests merged in 2023-11, with the labels that each got.

#43 [Expression Calculating] generated README.md by roby238 v1
  Expression_Calculating/README.md
Labels: Calculation, Y :ok_person: Done, Doc

#45 [Management] Update README.md
  Expression_Calculating/README.md
Labels: Calculation, Y :ok_person: Done, Z 9:hammer: Fixed, Doc

#48 [Expressing Calculating] updated calculator_module.py by roby238 #1238
  Expression_Calculating/calculator_module.py
Labels: Calculation, Y :ok_person: Done, Z 9:hammer: Fixed

#50 [Expression Calculating] updated calculator_module.py
  Expression_Calculating/calculator_module.py
Labels: Calculation, Y :ok_person: Done, Z :bug: Bug, Z 9:hammer: Fixed

#51 [Expression Calculating] updated calculator_module.py
  Expression_Calculating/calculator_module.py
Labels: Calculation, Y :ok_person: Done, Z :bug: Bug, Z 9:hammer: Fixed

#53 [Image Preprocessing] Documentation
  Mergy_Hand_Pose_Estimation_Preprocessing/preprocessing_module.py
Labels: Image Preprocessing, Doc

#58 [Management] Delete Mergy_Hand_Pose_Estimation_Preprocessing/__pycach…
  Mergy_Hand_Pose_Estimation_Preprocessing/__pycache__/hand_pattern_recognition_module.cpython-38.pyc
  Mergy_Hand_Pose_Estimation_Preprocessing/__pycache__/hand_pose_estimation_show_module.cpython-38.pyc
  Mergy_Hand_Pose_Estimation_Preprocessing/__pycache__/image_inferencing_module.cpython-38.pyc
  Mergy_Hand_Pose_Estimation_Preprocessing/__pycache__/preprocessing_module.cpython-38.pyc
Labels: Y :ok_person: Done, Z 9:hammer: Fixed

#59 [Management] updated REAMD.md
  README.md
  doc/Untitled Diagram.drawio
Labels: Y :ok_person: Done, AA :page_facing_up: Doc

#64 Ai modeling readme
  AI_Modeling/README.md
  AI_Modeling/training_result.md
  doc/[Intel] AI Project TEAM01 BoardMaestro_chungu.pptx
Labels: AI Modeling, Y :ok_person: Done, AA :page_facing_up: Doc

#72 Update README.md
  image_preprocessing/README.md
Labels: Image Preprocessing, Y :ok_person: Done, AA :page_facing_up: Doc

#74 Update README.md
  hand_pose_estimation/README.md
Labels: Pose Estimation, Y :ok_person: Done, AA :page_facing_up: Doc

#75 Update README.md
  hand_pattern_recognition/README.md
Labels: Pose Estimation, Y :ok_person: Done, AA :page_facing_up: Doc
