Repository Intel-Edge-AI-SW-Developers-2nd-Team-1/BoardMaestro, pull requests merged in 2024-05, with the labels that each got.

#81 Update preprocessing_module.py
  image_preprocessing/preprocessing_module.py
Labels: Z 9:hammer: Fixed

#83 Modify UI view dynamically
  demo_test/ui_test.py
Labels: Z 9:hammer: Fixed, User Interface

#84 [Refactor] Reform old Mediapipe Pose Estimation to OpenVINO Hand Tracker
  ai_modeling/model/hand_landmark_FP32.bin
  ai_modeling/model/hand_landmark_FP32.xml
  ai_modeling/model/palm_detection_FP32.bin
  ai_modeling/model/palm_detection_FP32.xml
  demo_test/ui_test_origin.py
  demo_test/ui_test_reform.py
  hand_pattern_recognition/hand_pattern_recognition_module.py
  hand_pose_estimation/hand_pose_estimation_module.py
  hand_pose_estimation/hand_tracker_module.py
  image_preprocessing/preprocessing_module.py
  run.sh
Labels: Pose Estimation, Image Preprocessing, AI Modeling, Y :ok_person: Done, Z :hammer: Fixed, User Interface
