Repository Intel-Edge-AI-SW-Developers-2nd-Team-1/BoardMaestro, pull requests merged in 2024-06, with the labels that each got.

#87 [Refactor] fix directory dependency issue
  demo_test/ui_test_reform.py
  hand_pose_estimation/hand_tracker_module.py
Labels: Pose Estimation, Y :ok_person: Done, Z :bug: Bug, Z :hammer: Fixed

#85 [Deployment] Update about optimization prerpocessing
  optimization_test/Result/Result_0.jpg
  optimization_test/Result/Result_1.jpg
  optimization_test/Result/Result_2.jpg
  optimization_test/__pycache__/optimization_preprocessing_module.cpython-310.pyc
  optimization_test/number.png
  optimization_test/optimization_demo.py
  optimization_test/optimization_preprocessing_module.py
  optimization_test/optimization_preprocessing_test1.py
  optimization_test/secondary_memory_test.py
  optimization_test/test.jpg
Labels: Image Preprocessing, Y :ok_person: Done

#88 [Deploy] update requirements.txt
  requirements.txt
Labels: Y :ok_person: Done, User Interface

#89 [Calculator] fix single operator issue like -1 or -1*-5
  expression_calculating/calculator_module.py
Labels: Calculation, Y :ok_person: Done, Z :bug: Bug, Z :hammer: Fixed

#90 [Calculator] update jetson file and fix cons & func issue
  ai_modeling/model/label_schema.json
  expression_calculating/calculator_module.py
Labels: Calculation, Y :ok_person: Done, Z :bug: Bug, Z :hammer: Fixed

#91 [UI] update UI
  demo_test/ui_test_reform.py
Labels: User Interface

#92 [Calculator] fix operator priority issue
  expression_calculating/calculator_module.py
Labels: Calculation, Y :ok_person: Done, Z :bug: Bug, Z :hammer: Fixed

#94 [Chore] update README.md
  README.md
Labels: AA :page_facing_up: Doc
